build: build-parser

build-parser:
    cargo build -p vic3-parser --target wasm32-wasip1 --release
    cp ../../target/wasm32-wasip1/release/vic3-parser.wasm parser.wasm

test:
    cargo test -p vic3-parser
