build: build-parser

build-parser:
    cargo build -p stellaris-parser --target wasm32-wasip1 --release
    cp ../../target/wasm32-wasip1/release/stellaris-parser.wasm parser.wasm

test:
    cargo test -p stellaris-parser
