name: Check Rust

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@a3324fb0eb94b8230ec968c3389c1b7929fc2f3b # v2
        with:
          tool: just

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Test Rust workspace
        run: just test-rust

      - name: Lint Rust workspace
        run: just lint-rust
